version: 2
jobs:
    build:
        docker:
            - image: rpseq/docker-latex
        steps:
            - checkout
            - run:
                name: gitConfig
                command: |
                    git config --global user.email "ryan.smith.p@gmail.com"
                    git config --global user.name "RPSeq"
            - run:
                name: clean
                command: rm ryan_p_smith_resume.pdf
            - run:
                name: makePDF
                command: latexmk -pdf ryan_p_smith_resume.tex
            - run:
                name: push
                command: |
                    git commit -am "Auto-build $CIRCLE_BUILD_NUM [ci skip]"
                    git push